title = "MagicRune Gitleaks Rules"

[allowlist]
description = "Allow sample fixtures and benign local endpoints"
paths = [
  '''^samples/.*$''',
  '''^policies/.*\.ya?ml$'''
]
regexes = [
  '''NATS_URL\s*=\s*["']?nats://localhost:\d+["']?''',
  '''NATS_(STREAM|DURABLE)\s*=\s*["']?(RUN|RUN_WORKER)["']?'''
]

[[rules]]
id = "generic-api-key"
description = "Generic API Key"
regex = '''(?i)(api[_\-\s]?key|apikey)[[:space:]]*[=:][[:space:]]*['\"]?[a-zA-Z0-9\-_]{16,}['\"]?'''
keywords = ["api", "key", "apikey"]

[rules.allowlist]
regexTarget = "match"
regexes = ['''(YOUR_API_KEY|PLACEHOLDER|example|test|dummy|fake)''']

[[rules]]
id = "private-key"
description = "Private Key"
regex = '''(?i)(private[_\-\s]?key)[[:space:]]*[=:][[:space:]]*['\"]?[a-zA-Z0-9\-_]{16,}['\"]?'''
keywords = ["private", "key"]

[rules.allowlist]
regexTarget = "match"
regexes = ['''(test|example|dummy|fake|placeholder)''']
