[package]
name = "bootstrapped"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "A bootstrapped Rust/WASM edge application"
repository = "https://github.com/NishizukaKoichi/bootstrapped"
default-run = "bootstrapped"

[features]
default = ["std"]
std = []
wasm = []

[dependencies]
thiserror = "2.0"
serde = { version = "1.0", features = ["derive"], default-features = false }
serde_json = { version = "1.0", default-features = false, features = ["alloc"] }
async-trait = "0.1"
base64 = "0.22"
clap = { version = "4.5", features = ["derive"] }
serde_yaml = "0.9"
sha2 = "0.10"
hex = "0.4"


[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = "0.2"
js-sys = "0.3"

[dev-dependencies]
tokio = { version = "1.42", features = ["full"] }
