name: sec-ci
on:
  pull_request:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  sec-ci:
    name: sec-ci
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - uses: dtolnay/rust-toolchain@7b1c307e0dcbda6122208f10795a713336a9b35a # stable
      - uses: Swatinem/rust-cache@82a92a6e8fbeee089604da2575dc567ae9ddeaab # v2.7.5
      
      - name: Install security tools
        run: |
          cargo install cargo-audit --locked --version 0.21.0
          cargo install cargo-deny --locked --version 0.16.3
      
      - name: Create Cargo.lock if missing
        run: |
          if [ ! -f Cargo.lock ]; then
            cargo generate-lockfile
          fi
      
      - name: Security audit
        run: cargo audit -D warnings
      
      - name: Dependency check  
        run: cargo deny check advisories licenses bans sources
      
      - name: Gitleaks scan
        uses: gitleaks/gitleaks-action@4c7a9c606108c5296263080852cc0f5a2f51f470 # v2.3.9
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITLEAKS_VERSION: v8.22.1