name: sec-ci
on:
  pull_request:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  sec-ci:
    name: sec-ci
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          fetch-depth: 0
      - uses: dtolnay/rust-toolchain@7b1c307e0dcbda6122208f10795a713336a9b35a # stable
        with:
          toolchain: stable
      - uses: Swatinem/rust-cache@82a92a6e8fbeee089604da2575dc567ae9ddeaab # v2.7.5
      
      - name: Install cargo-binstall
        run: |
          curl -L --retry 5 --retry-delay 1 https://github.com/cargo-bins/cargo-binstall/releases/latest/download/cargo-binstall-x86_64-unknown-linux-musl.tgz | tar xvz -C ~/.cargo/bin
          
      - name: Install security tools
        run: |
          cargo binstall --no-confirm --no-symlinks cargo-audit --version 0.21.0
          cargo binstall --no-confirm --no-symlinks cargo-deny --version 0.16.3
      
      - name: Create Cargo.lock if missing
        run: |
          if [ ! -f Cargo.lock ]; then
            cargo generate-lockfile
          fi
      - name: Update lockfile (prune unused)
        run: cargo update -q
      
      - name: Security audit (ignore known advisories)
        run: |
          cargo audit -D warnings -c .cargo/audit.toml \
            --ignore RUSTSEC-2025-0046 \
            --ignore RUSTSEC-2024-0438 \
            --ignore RUSTSEC-2024-0436 \
            --ignore RUSTSEC-2020-0168 \
            --ignore RUSTSEC-2024-0442
      
      - name: Dependency check  
        run: cargo deny check advisories licenses bans sources
      
      - name: Gitleaks scan
        uses: gitleaks/gitleaks-action@v2
        with:
          args: --redact --config .gitleaks.toml --no-git
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
