name: Security
on:
  pull_request:
  workflow_dispatch:
jobs:
  audit_and_deny:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Install tools
        run: |
          cargo install cargo-audit --locked
          cargo install cargo-deny --locked
      - name: cargo audit
        run: cargo audit -D warnings
      - name: cargo deny
        run: cargo deny check advisories licenses bans sources
  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: gitleaks
        uses: gitleaks/gitleaks-action@v2
        with:
          args: detect --redact --no-banner